export const careers = [
    {
        name: 'Mechanical Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Civil Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Electrical Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Software Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Aerospace Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Biomedical Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Chemical Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Computer Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Environmental Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Nuclear Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Industrial Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Petroleum Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Robotics Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Systems Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Marine Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Materials Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Geotechnical Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Mining Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Structural Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
    {
        name: 'Automotive Engineer',
        type: 'stuff',
        averagepay: 0,
        worklife: 'a',
        image: '',
        url: '',
    },
]
